
- name: Run Bash script with arguments on slave
  hosts: slave
  tasks:
    - name: Transfer Bash script to slave
      copy:
        src: lampdeploy.sh
        dest: /tmp/lampdeploy.sh
        mode: "0755"  # Ensure the script is executable

    - name: Execute Bash script with arguments on slave
      shell: /tmp/lampdeploy.sh https://github.com/laravel/laravel.git laravel laraveldb db_user Alpha_Tango1 laravel development 192.168.50.15